### ISSUE TITLE
Exception_During_Work

### ISSUE THREAD

**Issue by mateuszhyski** [SCADA-LTS/Scada-LTS-E2E#118]
After update mvn to expected version, and update of course chrome webbrowser to version 83, project on branche #114 has been build. After run a tests by command in terminal, I have :
![e2e_with_mvn_version_expected](https://user-images.githubusercontent.com/3029545/85031463-ff926000-b17e-11ea-8754-3243f95ed081.png)

Can you give me some tips, what should I do, steps etc.
Thank you.

**Comment by Limraj** [comment]
Please follow my instructions in the email and everything will be fine. :)
