### ISSUE TITLE
Scada-LTS "Expected property name or '}' in JSON at position 1"

### ISSUE THREAD

**Issue by AristotelesMelo** [SCADA-LTS/Scada-LTS-E2E#193]
Sorry for using your private email, but I am unable to publish this question on github.

We are located in Brazil and Scada-LTS is new to us.

I installed the scada-lts 2.6.18 version with Mysql 5.7 on Windows installed on AWS and everything is ok.

I created a "Graphical-View" with an "Enhanced image Chart" component that works fine when I access it locally, ie the browser installed on AWS windows.

When accessing remotely I get the following error:  "Expected property name or '}' in JSON at position 1"

Do you have any idea what this error could be?

**Comment by Limraj** [comment]
Hi @AristotelesMelo,

You added an issue in the Scada-LTS-E2E project, i.e. automatic tests for Scada-LTS. Here is the Scaca-LTS project:
https://github.com/SCADA-LTS/Scada-LTS

If the issue persists, I suggest creating a more specific issue in the Scada-LTS project.

Regards,
Kamil Jarmusik
