### ISSUE TITLE
Project is not build succesfully

### ISSUE THREAD

**Issue by mateuszhyski** [SCADA-LTS/Scada-LTS-E2E#56]
During checkout project and do steps ( as in instruction) - run command mvn clean install, I have 

![mvn_clean_install](https://user-images.githubusercontent.com/3029545/74780453-eb595780-529f-11ea-9448-9fda782e1a66.png)

Please write what I should do to build sucessfully project?

**Comment by Limraj** [comment]
You need java 1.8 and maven in version 3.6.1, this forces the enforcer, as if you had made the screen a little higher then it would probably be written. 
In addition, you must install the Lombok plugin and enable the annotation processor in Intellij File -> Settings:
![anno](https://user-images.githubusercontent.com/35842300/74794740-52890300-52c4-11ea-82ea-fe49ded413e4.png)

**Comment by mateuszhyski** [comment]
Why we need maven in version 3.6.1? If we need to install Lombok plugin, this should be in instruction.

**Comment by mateuszhyski** [comment]
Please reopen this issue because I trying to build this project with your tips.

**Comment by Limraj** [comment]
If you use them, it will solve the problem you pointed out.

śr., 19 lut 2020 o 10:44 mateuszhyski <notifications@github.com> napisał(a):

**Comment by mateuszhyski** [comment]
I would like to check this (with your tips) and then I will give you status that problem has been solved or not.So this issue is not solved yet.

**Comment by mateuszhyski** [comment]
I have done your tips but still have this issue. Below are versions: java and mvn.Can you tell me what else to do?
![Screenshot from 2020-02-19 11-07-56](https://user-images.githubusercontent.com/3029545/74824124-1c6d7280-5308-11ea-8a96-fa0823ab194a.png)

**Comment by Limraj** [comment]
During our conversation, I asked if you managed to solve the problem, I did
not get any answer, neither confirming or negative, I thought that yes, and
I know this problem.

śr., 19 lut 2020 o 10:58 mateuszhyski <notifications@github.com> napisał(a):

**Comment by Limraj** [comment]
![maven config](https://user-images.githubusercontent.com/35842300/74826585-209b8f00-530c-11ea-9a10-82575b7a492e.png)
1) Download maven 3.6.1:
https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/
2) Extract to the selected location;
3) Set the environment variable MVN_HOME and add to PATH in Windows, in
linux do export
4) In Intellij: File-> Settings -> ... -> Maven (you can enter in the
search window it will find you without unnecessary clicking) Set the path
to your maven;
5) Click File-> Settings -> Invalide Caches and restart
6) Check the mvn -v version in the Intellij terminal

śr., 19 lut 2020 o 11:10 mateuszhyski <notifications@github.com> napisał(a):

**Comment by Limraj** [comment]
You can also check in a terminal outside Intellij if the environment
variable is set correctly;

śr., 19 lut 2020 o 11:22 Kamil Tomasz Jarmusik <kamil.jarmusik@gmail.com>
napisał(a):

**Comment by Limraj** [comment]
Generally, the enforcer keeps an eye on the java and maven versions.

śr., 19 lut 2020 o 11:23 Kamil Tomasz Jarmusik <kamil.jarmusik@gmail.com>
napisał(a):

**Comment by Limraj** [comment]
There is a problem with newer versions of Maven in Intellij, it is the
latest version that does not create problems when working with Intellij.

śr., 19 lut 2020 o 11:28 Kamil Tomasz Jarmusik <kamil.jarmusik@gmail.com>
napisał(a):
