### ISSUE TITLE
After_update_Chrome_WebBrowser_Part_Of_Tests_PointLinks_DoNotWork

### ISSUE THREAD

**Issue by mateuszhyski** [SCADA-LTS/Scada-LTS-E2E#78]
After update webbrowser Chrome, I run this test(jar file) with parameter -H but I have:
![Screenshot from 2020-03-25 12-39-31](https://user-images.githubusercontent.com/3029545/77533168-aaec8b00-6e96-11ea-958d-4fd7c3331e08.png)

**Comment by Limraj** [comment]
As I wrote in the emails, you should install the latest stable version of the chrome 80 browser.

**Comment by mateuszhyski** [comment]
There was another working E2E tests which won't finished his work. I terminated those tests. This error not appear.
